AESoft/AESoftWare/Models/ContaCorrente.cs
namespace AESoftWare.Models
{
    public class ContaCorrente
    {
        public int NumeroConta{ get; set; }
        public double Saldo{ get; set; }
        public string Titular { get; set; }
        public double Valor { get; set; }
        public bool RealizarSaque(double Valor)
        {
            if (Valor > Saldo)
                return false;

            Saldo -= Valor;
            return true;
        }
        public void RealizarDeposito(double Valor)
        {
            Saldo += Valor;
        }
    }
}

AESoft/AESoftWare/Models/ContarCorrenteValorModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AESoftWare.Models
{
    public class ContarCorrenteValorModel
    {
        public ContaCorrente Conta { get; set; }
        public double valor { get; set; }
    }
}

AESoft/AESoftWare/Models/ErrorViewModel.cs
using System;

namespace AESoftWare.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AESoft/AESoftWare/Models/ListaContas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AESoftWare.Models
{
    public class ListaContas
    {
        List<ContaCorrente> listasContas { get; set; }
    }
}

AESoft/AESoftWare/Models/ValorModel.cs
namespace AESoftWare.Models
{
    public class ValorModel
    {
        public double Valor { get; set; }
    }
}

AESoft/AESoftWare/Controllers/ContaCorrenteController.cs
using AESoftWare.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AESoftWare.Controllers
{
    public class ContaCorrenteController : Controller
    {
        List<ContaCorrente> listConta;
        ContaCorrente conta;
        public ContaCorrenteController(List<ContaCorrente> lista)
        {
            listConta = lista;
        }
        // GET: ContaCorrenteController
        public ActionResult Index()
        {
            return View();
        }
        // GET: ContaCorrenteController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        // GET: ContaCorrenteController/Create
        public IActionResult ContaCorrenteCreate()
        {
            return View();
        }
        public ActionResult ConsultarDetalhes(int numeroConta)
        {
            conta = listConta.Find(x => x.NumeroConta == numeroConta);
            return View(conta);
        }
        public ActionResult RealizarSaque(ContaCorrente con)
        {
            conta = listConta.Find(x => x.NumeroConta == con.NumeroConta);
            return View(new ContarCorrenteValorModel() { Conta = conta, valor = 0 });
        }

        [HttpPost]
        public IActionResult Edit(ContarCorrenteValorModel contaV)
        {
            conta = listConta.Find(x => x.NumeroConta == contaV.Conta.NumeroConta);

            var realizado = conta.RealizarSaque(contaV.Conta.Valor);
            if (realizado)
                return RedirectToAction("RealizarSaque", conta);
            return RedirectToAction("RealizarSaque", conta);
        }
        public ActionResult RealizarDeposito(ContaCorrente con)
        {
            conta = listConta.Find(x => x.NumeroConta == con.NumeroConta);
            return View(new ContarCorrenteValorModel() { Conta = conta, valor = 0 });
        }
        public IActionResult EditDeposito(ContarCorrenteValorModel contaV)
        {
            conta = listConta.Find(x => x.NumeroConta == contaV.Conta.NumeroConta);

            conta.RealizarDeposito(contaV.Conta.Valor);
            return RedirectToAction("RealizarDeposito", conta);
        }
        // POST: ContaCorrenteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ContaCorrente conta)
        {
            try
            {
                listConta.Add(conta);
                return RedirectToAction(nameof(ContaCorrentes));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            listConta.RemoveAll(x => x.NumeroConta == id);

            return View(listConta);
        }

        public IActionResult ContaCorrentes()
        {

            return View(listConta);
        }

        // POST: ContaCorrenteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //public bool RealizarSaque(ContaCorrente conta)
        //{
        //    if (conta. > Saldo)
        //        return false;

        //    Saldo -= Valor;
        //    return true;
        //}
    }
}

AESoft/AESoftWare/Controllers/HomeController.cs
using AESoftWare.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AESoftWare.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

       
       

      
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AESoft/AESoftWare/Views/ContaCorrente/ConsultarDetalhes.cshtml
@model AESoftWare.Models.ContaCorrente

@{
}
<h1>Detalhes da Conta Corrente</h1>

<h4>Detalhes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ContaCorrenteCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NumeroConta" class="control-label"></label>
                <input asp-for="NumeroConta" class="form-control" readonly />
                <span asp-validation-for="NumeroConta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Saldo" class="control-label"></label>
                <input asp-for="Saldo" class="form-control" readonly/>
                <span asp-validation-for="Saldo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titular" class="control-label"></label>
                <input asp-for="Titular" class="form-control" readonly/>
                <span asp-validation-for="Titular" class="text-danger"></span>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ContaCorrentes">Back to ContaCorrentes</a>
</div>

AESoft/AESoftWare/Views/ContaCorrente/ContaCorrenteCreate.cshtml
@model AESoftWare.Models.ContaCorrente

@{
    ViewData["Title"] = "ContaCorrenteCreate";
}

<h1>Criação de Conta Corrente</h1>

<h4>Conta Corrente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Create", "ContaCorrente", FormMethod.Post))
        {
            <form asp-action="ContaCorrenteCreate">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="NumeroConta" class="control-label"></label>
                    <input asp-for="NumeroConta" class="form-control" />
                    <span asp-validation-for="NumeroConta" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Saldo" class="control-label"></label>
                    <input asp-for="Saldo" class="form-control" />
                    <span asp-validation-for="Saldo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Titular" class="control-label"></label>
                    <input asp-for="Titular" class="form-control" />
                    <span asp-validation-for="Titular" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label>Buttão</label>
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        }
        </div>
</div>

<div>
    <a asp-action="ContaCorrentes">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AESoft/AESoftWare/Views/ContaCorrente/ContaCorrentes.cshtml
@model IEnumerable<AESoftWare.Models.ContaCorrente>

@{
    ViewData["Title"] = "View";
}

<h1>Lista de Contas</h1>

<p>
    <a asp-action="ContaCorrenteCreate">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumeroConta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Saldo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titular)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NumeroConta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Saldo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Titular)
                </td>
                <td>
                    @Html.ActionLink("Sacar", "RealizarSaque", new { numeroConta = item.NumeroConta }) |
                    @Html.ActionLink("Details", "ConsultarDetalhes", new { numeroConta = item.NumeroConta }) |
                    @Html.ActionLink("Deposito", "RealizarDeposito", new { numeroConta = item.NumeroConta  })
                </td>
            </tr>
        }
    </tbody>
</table>

AESoft/AESoftWare/Views/ContaCorrente/RealizarDeposito.cshtml
@model AESoftWare.Models.ContarCorrenteValorModel
@{

}
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("EditDeposito", "ContaCorrente", FormMethod.Post))
        {
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Conta.NumeroConta" class="control-label"></label>
                    <input asp-for="Conta.NumeroConta" class="form-control" readonly />
                    <span asp-validation-for="Conta.NumeroConta" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Conta.Saldo" class="control-label"></label>
                    <input asp-for="Conta.Saldo" class="form-control" readonly />
                    <span asp-validation-for="Conta.Saldo" class="text-danger" onchange=""></span>
                </div>
                <div class="form-group">
                    <label id="valor"asp-for="Conta.Valor" class="control-label"></label>
                    <input asp-for="Conta.Valor" class="form-control" />
                    <span asp-validation-for="Conta.Valor" class="text-danger"></span>
                </div>
                <label>
                    <button class="btn btn-info" type="submit" id="addressSearch">
                        Depósito
                    </button>
                </label>
            </form>
        }
    </div>
</div>
<div>
    <a asp-action="ContaCorrentes">Back to List</a>
</div>

AESoft/AESoftWare/Views/ContaCorrente/RealizarSaque.cshtml
@model AESoftWare.Models.ContarCorrenteValorModel
@{

}
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Edit", "ContaCorrente", FormMethod.Post))
        {
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Conta.NumeroConta" class="control-label"></label>
                    <input asp-for="Conta.NumeroConta" class="form-control" readonly />
                    <span asp-validation-for="Conta.NumeroConta" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Conta.Saldo" class="control-label"></label>
                    <input asp-for="Conta.Saldo" class="form-control" readonly />
                    <span asp-validation-for="Conta.Saldo" class="text-danger" onchange=""></span>
                </div>
                <div class="form-group">
                    <label id="valor"asp-for="Conta.Valor" class="control-label"></label>
                    <input asp-for="Conta.Valor" class="form-control" />
                    <span asp-validation-for="Conta.Valor" class="text-danger"></span>
                </div>
                <label>
                    <button class="btn btn-info" type="submit" id="addressSearch">
                        Saque
                    </button>
                </label>
            </form>
        }
    </div>
</div>
<div>
    <a asp-action="ContaCorrentes">Back to List</a>
</div>

AESoft/AESoftWare/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AESoft/AESoftWare/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AESoftWare</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AESoftWare</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ContaCorrente" asp-action="ContaCorrentes">Lista de Contas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ContaCorrente" asp-action="ContaCorrenteCreate">Criar Conta</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ContaCorrente" asp-action="RealizarSaque">Realizar Saque</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Realizar Depósito</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Consulta saldo</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AESoftWare - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>